# Language used usually but in or case we wish to not run
# the default pip install command hence just setting the 
# language to minimal will work.
language: minimal


jobs:
  include:
    # Stage to run tests
    # - state: Run Tests 
    #   name: "Tests Stage"
    # - script:
    #   - echo "Stage for tests"

    # Stage to create the infrastructure
    - stage: Infrastructure
      name: "Setup Infrastructure"
    - script:
      - export VER="0.12.21"
      - wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
      - unzip terraform_${VER}_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - chmod +x travis-ci-scripts/create_infrastructure.sh
      - ./travis-ci-scripts/create_infrastructure.sh
  
    # Stage to build and push image
    - stage: Build docker Image
      services:
        - docker
      name: "Build image"
    - script:
      - chmod +x travis-ci-scripts/build_docker_image.sh
      - ./travis-ci-scripts/build_docker_image.sh

    # Stage to deploy application
    - stage: Deploy
      name: "Deploy to DO"
      sudo: required
    - script:
      - chmod +x travis-ci-scripts/deployment.sh
      - ./travis-ci-scripts/deployment.sh

